### ISSUE TITLE
Compile bug: error: use of undeclared identifier 'llama_chat_builtin_templates' building 4265, only with `-DLLAMA_CURL=ON`

### ISSUE THREAD

**Issue by i0ntempest** [ggerganov/llama.cpp#10661]
### Git commit

59f4db1

### Operating systems

Mac

### GGML backends

Metal

### Problem description & steps to reproduce

Build with `-DLLAMA_CURL=ON`. Builds without this arg will succeed.

### First Bad Commit

I think its this one: https://github.com/ggerganov/llama.cpp/commit/642330ac7cea11dc1f9d3df2b8f3dbd10b5e3f3e#diff-f3a359c2393a8c0bf7cb0cbe9e4622c62366566bb4956ebf8d56e1bd196f8fe7R351
4231 and 4240 builds fine

### Relevant log output

```shell
[ 19%] Building CXX object src/CMakeFiles/llama.dir/unicode-data.cpp.o
[ 20%] Linking CXX executable ../../bin/llama-gguf
[ 20%] Built target llama-gguf
[ 21%] Linking CXX executable ../../bin/llama-gguf-hash
[ 21%] Built target llama-gguf-hash
[ 22%] Linking CXX shared library libllama.dylib
[ 22%] Built target llama
[ 22%] Building CXX object examples/simple/CMakeFiles/llama-simple.dir/simple.cpp.o
[ 22%] Building CXX object examples/run/CMakeFiles/llama-run.dir/run.cpp.o
[ 22%] Building CXX object common/CMakeFiles/common.dir/arg.cpp.o
[ 23%] Building CXX object examples/quantize-stats/CMakeFiles/llama-quantize-stats.dir/quantize-stats.cpp.o
[ 24%] Building CXX object examples/simple-chat/CMakeFiles/llama-simple-chat.dir/simple-chat.cpp.o
[ 26%] Building CXX object common/CMakeFiles/common.dir/common.cpp.o
[ 26%] Building CXX object common/CMakeFiles/common.dir/log.cpp.o
[ 26%] Building CXX object common/CMakeFiles/common.dir/ngram-cache.cpp.o
[ 26%] Building CXX object examples/llava/CMakeFiles/llava.dir/llava.cpp.o
[ 27%] Building CXX object common/CMakeFiles/common.dir/json-schema-to-grammar.cpp.o
[ 28%] Building C object tests/CMakeFiles/test-c.dir/test-c.c.o
[ 29%] Building CXX object examples/llava/CMakeFiles/llava.dir/clip.cpp.o
[ 29%] Building CXX object common/CMakeFiles/common.dir/sampling.cpp.o
[ 30%] Building CXX object common/CMakeFiles/common.dir/console.cpp.o
[ 30%] Building CXX object common/CMakeFiles/common.dir/speculative.cpp.o
[ 31%] Linking C executable ../bin/test-c
[ 31%] Built target test-c
[ 32%] Linking CXX executable ../../bin/llama-simple
[ 32%] Built target llama-simple
[ 32%] Linking CXX executable ../../bin/llama-simple-chat
/Users/Admin/Downloads/llama.cpp-4265/common/arg.cpp:353:19: error: use of undeclared identifier 'llama_chat_builtin_templates'
  353 |     int32_t res = llama_chat_builtin_templates(nullptr, 0);
      |                   ^
/Users/Admin/Downloads/llama.cpp-4265/common/arg.cpp:355:11: error: use of undeclared identifier 'llama_chat_builtin_templates'
  355 |     res = llama_chat_builtin_templates(supported_tmpl.data(), supported_tmpl.size());
      |           ^
[ 32%] Built target llama-simple-chat
[ 33%] Linking CXX executable ../../bin/llama-run
[ 33%] Built target llama-run
2 errors generated.
make[2]: *** [common/CMakeFiles/common.dir/arg.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 33%] Linking CXX executable ../../bin/llama-quantize-stats
[ 33%] Built target llama-quantize-stats
[ 33%] Built target llava
[ 34%] Linking CXX static library libllava_static.a
[ 34%] Linking CXX shared library libllava_shared.dylib
[ 34%] Built target llava_static
[ 34%] Built target llava_shared
make[1]: *** [common/CMakeFiles/common.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by ggerganov** [comment]
There is very likely something wrong in your environment. Maybe you have some old `llama.h` somewhere in your include paths. Not sure. But the CI is passing and I am building on Mac OS with the `LLAMA_CURL` flag successfully.

**Comment by i0ntempest** [comment]
Should have thought about that. Removed the previous version 4240 and it built fine.
