### ISSUE TITLE
Swift/Xcode build errors since #4935: `spm-headers/llama.h:235:9 Unknown type name 'ggml_backend_sched_eval_callback'`

### ISSUE THREAD

**Issue by brittlewis12** [ggerganov/llama.cpp#5029]
Since b1901 (rev 44a1a4a41a4c0b03afaa7d9e06bcbc7cf95aa1e6 #4935), I've been unable to build llama.cpp with the provided Package.swift. I bisected back to this PR as the first breaking commit — b1900 (rev c918fe8dca8fa1c4602427e0a4b88e20046f6c34) seems to work well.

I'm not terribly comfortable with C++, so to my eye I don't see anything wrong with the patch. I noticed the lack of `GGML_API` prefix like other types in the file, ~but I tried changing that locally and didn't notice a difference, though it's very possible I applied said change incorrectly/incompletely.~ EDIT: it seems committing this change indeed resolved the visibility issue I experienced as a result. Proposed a patch: #5030

I would be more than happy to share any other relevant information or test any proposed fixes to the extent that would be helpful!

---

Here's the full error log:
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/tito/code/llama.cpp/spm-headers/llama.h"
        ^
/Users/tito/code/llama.cpp/spm-headers/llama.h:235:9: error: unknown type name 'ggml_backend_sched_eval_callback'
        ggml_backend_sched_eval_callback cb_eval;
```

**Comment by ggerganov** [comment]
It should work without `GGML_API` - I think your changes coincided with a `ggml` package update. If you init cleanly the Swift project it should work without modifications

**Comment by ggerganov** [comment]
Well, it's pretty much the same thing, because I manually update the `release` branch when I have to update the Swift package. Overall, the current process is not optimal, but I think we are converging to a stable solution and such kind of problems will happen less often

**Comment by brittlewis12** [comment]
I can very much appreciate the underlying complexity you're wrangling, and I have no doubt it will continue to improve with time. Thanks again for all your hard work on these fantastic projects!
