### ISSUE TITLE
Vulkan build on Windows cmake broken since commit 172ac826 (PR #5182)

### ISSUE THREAD

**Issue by stduhpf** [ggerganov/llama.cpp#5191]
Trying to Build using cmake on windows : 
```
> cmake .. -DBUILD_SHARED_LIBS=OFF -DLLAMA_VULKAN=ON -G "Visual Studio 17 2022" -A x64
> cmake --build . --config Release
```
The compilation breaks when building `ggml-vulkan.cpp`, somehow the compiler can't find vulkan.hpp

I'm confused because the compilation works fine on [0cc4m's original PR branch](https://github.com/0cc4m/koboldcpp/tree/vulkan), using the exact same commands; on the same machine.

**Comment by stduhpf** [comment]
Ok after a quick investigation it seems that commit #5182 Is ironically what broke the building for me.

**Comment by netrunnereve** [comment]
@stduhpf Is your actual error message the same as the one below? I don't have Windows so I can't test this.
```
  Generating Code...
  ggml-vulkan.cpp
C:\Users\Sora\Desktop\git\llama.cpp\ggml-vulkan.cpp(7,10): fatal  error C1083: Cannot open include file: 'vulkan/vulkan
.hpp': No such file or directory [C:\Users\Sora\Desktop\git\llama.cpp\vulkan\ggml.vcxproj]
```
@sorasoras (I'll respond to you here instead of the closed PR ticket) You might want to try diffing the CMake linker logs (from the CMake output folder) from before and after #5182 to see what has changed. Also try grepping for vulkan.hpp in the CMake output to see if there are any clues related to that. For some strange reason Windows isn't picking up your system Vulkan headers after my update.

**Comment by stduhpf** [comment]
> @stduhpf Is your actual error message the same as the one below? I don't have Windows so I can't test this.
> 
> ```
>   Generating Code...
>   ggml-vulkan.cpp
> C:\Users\Sora\Desktop\git\llama.cpp\ggml-vulkan.cpp(7,10): fatal  error C1083: Cannot open include file: 'vulkan/vulkan
> .hpp': No such file or directory [C:\Users\Sora\Desktop\git\llama.cpp\vulkan\ggml.vcxproj]
> ```
> 
> @sorasoras (I'll respond to you here instead of the closed PR ticket) You might want to try diffing the CMake linker logs (from the CMake output folder) from before and after #5182 to see what has changed. Also try grepping for vulkan.hpp in the CMake output to see if there are any clues related to that. For some strange reason Windows isn't picking up your system Vulkan headers after my update.

yes, same error. here is the beginning between the verbose cmake logs (master vs last working commit)
```diff
@@ -1,5 +1,5 @@
 Version MSBuild 17.7.2+d6990bcfa pour .NET Framework
-La g├®n├®ration a d├®marr├® 29/01/2024 22:50:41.
+La g├®n├®ration a d├®marr├® 29/01/2024 22:51:54.
 
      1>Projet "C:\Users\llm\llama.cpp\buildvk\ALL_BUILD.vcxproj" sur le noud 1 (cibles par d├®faut).
      1>Le projet "C:\Users\llm\llama.cpp\buildvk\ALL_BUILD.vcxproj" (1) g├®n├¿re "C:\Users\llm\llama.cpp\buildvk\ZERO_CHECK.vcxproj" (2) sur le noud 1 (cibles par d├®faut).
@@ -15,7 +15,7 @@ La g├®n├®ration a d├®marr├® 29/01/2024 22:50:41.
          Suppression du fichier "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
          Mise ├á jour de l'horodatage "x64\Release\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
      2>G├®n├®ration du projet "C:\Users\llm\llama.cpp\buildvk\ZERO_CHECK.vcxproj" termin├®e (cibles par d├®faut).
-     1>Le projet "C:\Users\llm\llama.cpp\buildvk\ALL_BUILD.vcxproj" (1) g├®n├¿re "C:\Users\llm\llama.cpp\buildvk\ggml.vcxproj" (5) sur le noud 4 (cibles par d├®faut).
+     1>Le projet "C:\Users\llm\llama.cpp\buildvk\ALL_BUILD.vcxproj" (1) g├®n├¿re "C:\Users\llm\llama.cpp\buildvk\ggml.vcxproj" (5) sur le noud 3 (cibles par d├®faut).
      5>Le projet "C:\Users\llm\llama.cpp\buildvk\ggml.vcxproj" (5) g├®n├¿re "C:\Users\llm\llama.cpp\buildvk\ggml-vulkan.vcxproj" (6) sur le noud 2 (cibles par d├®faut).
      6>PrepareForBuild:
          Cr├®ation du r├®pertoire "ggml-vulkan.dir\Release\".
@@ -176,13 +176,1407 @@ La g├®n├®ration a d├®marr├® 29/01/2024 22:50:41.
      5>C:\Users\llm\llama.cpp\ggml-quants.c(9088,41): warning C4244: 'initialisation'┬á: conversion de 'int' en 'float', perte possible de donn├®es [C:\Users\llm\llama.cpp\buildvk\ggml.vcxproj]
      5>C:\Users\llm\llama.cpp\ggml-quants.c(9120,38): warning C4244: 'initialisation'┬á: conversion de 'int' en 'float', perte possible de donn├®es [C:\Users\llm\llama.cpp\buildvk\ggml.vcxproj]
          G├®n├®ration de code en cours...
-         C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\CL.exe /c /I"C:\Users\llm\llama.cpp\." /nologo /W3 /WX- /diagnostics:column /O2 /Ob2 /D _MBCS /D WIN32 /D _WINDOWS /D NDEBUG /D GGML_USE_VULKAN /D _CRT_SECURE_NO_WARNINGS /D _XOPEN_SOURCE=600 /D "CMAKE_INTDIR=\"Release\"" /Gm- /EHsc /MD /GS /arch:AVX2 /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"ggml.dir\Release\\" /Fd"ggml.dir\Release\ggml.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\Users\llm\llama.cpp\ggml-vulkan.cpp"
-         ggml-vulkan.cpp
-     5>C:\Users\llm\llama.cpp\ggml-vulkan.cpp(7,10): fatal  error C1083: Impossible d'ouvrir le fichier include┬á: 'vulkan/vulkan.hpp'┬á: No such file or directory [C:\Users\llm\llama.cpp\buildvk\ggml.vcxproj]
-     5>G├®n├®ration du projet "C:\Users\llm\llama.cpp\buildvk\ggml.vcxproj" termin├®e (cibles par d├®faut) -- ├ëCHEC.
-     1>G├®n├®ration du projet "C:\Users\llm\llama.cpp\buildvk\ALL_BUILD.vcxproj" termin├®e (cibles par d├®faut) -- ├ëCHEC.
+       Lib:
+         C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\Lib.exe /OUT:"ggml.dir\Release\ggml.lib" /NOLOGO /MACHINE:X64  /machine:x64 ggml.dir\Release\ggml.obj
+         "ggml.dir\Release\ggml-alloc.obj"
+         "ggml.dir\Release\ggml-backend.obj"
+         "ggml.dir\Release\ggml-quants.obj"
+         ggml.vcxproj -> C:\Users\llm\llama.cpp\buildvk\ggml.dir\Release\ggml.lib
+       FinalizeBuildStatus:
+  [rest of the build, I'm not pasting all of that here]
```

**Comment by netrunnereve** [comment]
Okay I think I know what the problem is. In #5182 I caused the compiler to include ggml-vulkan.cpp in both the "ggml" and "ggml-vulkan" CMake libraries, and the ggml library is then linked again with ggml-vulkan. For some strange reason Linux is fine with this and everything ran fine on my end.

I fixed this in my fork https://github.com/netrunnereve/llama.cpp, which compiles properly on Linux. Can you two try building that fork on Windows and see if it works? Here's the diff:
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 65a6f397..5fca876d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -423,10 +423,7 @@ if (LLAMA_VULKAN)
     if (Vulkan_FOUND)
         message(STATUS "Vulkan found")
 
-        set(GGML_HEADERS_VULKAN ggml-vulkan.h)
-        set(GGML_SOURCES_VULKAN ggml-vulkan.cpp)
-
-        add_library(ggml-vulkan STATIC ggml-vulkan.cpp ggml-vulkan.h)
+        add_library(ggml-vulkan OBJECT ggml-vulkan.cpp ggml-vulkan.h)
         if (BUILD_SHARED_LIBS)
             set_target_properties(ggml-vulkan PROPERTIES POSITION_INDEPENDENT_CODE ON)
         endif()
@@ -1008,7 +1005,6 @@ add_library(ggml OBJECT
             ggml-quants.h
             ${GGML_SOURCES_CUDA}    ${GGML_HEADERS_CUDA}
             ${GGML_SOURCES_OPENCL}  ${GGML_HEADERS_OPENCL}
-            ${GGML_SOURCES_VULKAN}  ${GGML_HEADERS_VULKAN}
             ${GGML_SOURCES_METAL}   ${GGML_HEADERS_METAL}
             ${GGML_SOURCES_MPI}     ${GGML_HEADERS_MPI}
             ${GGML_SOURCES_EXTRA}   ${GGML_HEADERS_EXTRA}
@@ -1090,7 +1086,7 @@ install(FILES ${CMAKE_CURRENT_BINARY_DIR}/LlamaConfig.cmake
         DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Llama)
 
 set(GGML_PUBLIC_HEADERS "ggml.h" "ggml-alloc.h" "ggml-backend.h"
-        "${GGML_HEADERS_CUDA}" "${GGML_HEADERS_OPENCL}" "${GGML_HEADERS_VULKAN}"
+        "${GGML_HEADERS_CUDA}" "${GGML_HEADERS_OPENCL}"
         "${GGML_HEADERS_METAL}" "${GGML_HEADERS_MPI}" "${GGML_HEADERS_EXTRA}")
 
 set_target_properties(ggml PROPERTIES PUBLIC_HEADER "${GGML_PUBLIC_HEADERS}")
```
Having ggml-vulkan built as the original static caused Linux CMake to error out with the errors below, but setting it to object like ROCM worked. @0cc4m is there a reason you built it as static?
```
[ 20%] Linking CXX executable ../../bin/benchmark
/usr/bin/ld: ../../libggml-vulkan.a(ggml-vulkan.cpp.o): in function `ggml_backend_vk_buffer_type_alloc_buffer(ggml_backe
nd_buffer_type*, unsigned long)':
ggml-vulkan.cpp:(.text+0x28fe): undefined reference to `ggml_backend_buffer_init'
/usr/bin/ld: ../../libggml-vulkan.a(ggml-vulkan.cpp.o): in function `ggml_backend_vk_host_buffer_type':
ggml-vulkan.cpp:(.text+0x2f61): undefined reference to `ggml_backend_cpu_buffer_type'
/usr/bin/ld: ggml-vulkan.cpp:(.text+0x2f71): undefined reference to `ggml_backend_cpu_buffer_type'
/usr/bin/ld: ggml-vulkan.cpp:(.text+0x2f81): undefined reference to `ggml_backend_cpu_buffer_type'
/usr/bin/ld: ../../libggml-vulkan.a(ggml-vulkan.cpp.o): in function `ggml_backend_vk_reg_devices':
ggml-vulkan.cpp:(.text+0x3009): undefined reference to `ggml_backend_register'
/usr/bin/ld: ../../libggml-vulkan.a(ggml-vulkan.cpp.o): in function `ggml_backend_vk_host_buffer_type_alloc_buffer(ggml_
backend_buffer_type*, unsigned long)':
ggml-vulkan.cpp:(.text+0x15a59): undefined reference to `ggml_backend_cpu_buffer_from_ptr'
/usr/bin/ld: ggml-vulkan.cpp:(.text+0x15b09): undefined reference to `ggml_backend_cpu_buffer_type'
/usr/bin/ld: ggml-vulkan.cpp:(.text+0x15b2c): undefined reference to `ggml_backend_buft_alloc_buffer'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/benchmark/CMakeFiles/benchmark.dir/build.make:102: bin/benchmark] Error 1
make[1]: *** [CMakeFiles/Makefile2:2181: examples/benchmark/CMakeFiles/benchmark.dir/all] Error 2
```

**Comment by 0cc4m** [comment]
@netrunnereve The CMake code was contributed by @SlyEcho early during Vulkan development. I normally don't use Cmake, so I didn't notice the problems. If you know how to fix it, please open a PR.

**Comment by stduhpf** [comment]
@netrunnereve Your fork fixes it on my end, thanks!

**Comment by SlyEcho** [comment]
Make a PR, @netrunnereve 

There are some issues on Windows with the static library which I didn't know at the time because I don't use Windows.
