### ISSUE TITLE
Compile bug: [SYCL] Build fails from the latest master

### ISSUE THREAD

**Issue by qnixsynapse** [ggerganov/llama.cpp#10518]
### Git commit

ab96610b1e58684bc5e8b810130c4cf6d8252e21

### Operating systems

Linux

### GGML backends

SYCL

### Problem description & steps to reproduce

```
cmake -B build -DGGML_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DGGML_SYCL_F16=ON && cmake --build build --config Release -j -v --target llama-server --target test-backend-ops

```

Seems to me a missing header file.
Intel OneAPI base toolkit version: 2024.1.0.596-3
OS: Arch Linux

### First Bad Commit

Possibly: 5a54af4d4f588f109f31e456483fdf77096399d9

### Relevant log output

```shell
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/common.hpp:19   :
18 | /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp#:i18n:c10l:u de fatal error: <sy'syclcompat/math.hpp' file not foundcl
compat/math.   h18p | p#>in
c      l| ud         ^~~~~~~~~~~~~~~~~~~~~e
 <syclcompat/math.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/element_wise.cpp:1:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/common.hpp:19:
/home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp:18:10: fatal error: 'syclcompat/math.hpp' file not found
   18 | #include <syclcompat/math.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/im2col.cpp:13:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/im2col.hpp:16:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/common.hpp:19:
/home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp:18:10: fatal error: 'syclcompat/math.hpp' file not found
   18 | #include <syclcompat/math.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/rope.cpp:1:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/rope.hpp:16:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/common.hpp:19:
/home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp:18:10: fatal error: 'syclcompat/math.hpp' file not found
   18 | #include <syclcompat/math.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/mmvq.cpp:1:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/mmvq.hpp:16:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/common.hpp:19:
/home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp:18:10: fatal error: 'syclcompat/math.hpp' file not found
   18 | #include <syclcompat/math.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/dmmv.cpp:1:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/convert.hpp:16:
In file included from /home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/common.hpp:19:
/home/qnixsynapse/Public/Projects/llamacpp/llama.cpp/ggml/src/ggml-sycl/dpct/helper.hpp:18:10: fatal error: 'syclcompat/math.hpp' file not found
   18 | #include <syclcompat/math.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
1 error generated.
make[3]: *** [ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/build.make:121: ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/conv.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/build.make:205: ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/mmvq.cpp.o] Error 1
make[3]: *** [ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/build.make:107: ggml/src/ggml-sycl/CMakeFiles/ggml-sycl.dir/concat.cpp.o] Error 1
1 error generated.
1 error generated.
1 error generated.
```

**Comment by 0xDEADFED5** [comment]
pretty sure it's using oneapi 2025 now?

**Comment by qnixsynapse** [comment]
Didn't received that update on Arch. Is it already released?

**Comment by NeoZhangJianyu** [comment]
oneAPI 2025.0 is already released.

**Comment by qnixsynapse** [comment]
hmm. The [latest version on arch](https://archlinux.org/packages/extra-staging/x86_64/intel-oneapi-basekit/) seems outdated. Looks like I have to download it manually.

Anyways, closing this issue for now.
