### ISSUE TITLE
Compile bug: undefined reference to std::filesystem

### ISSUE THREAD

**Issue by Clauszy** [ggerganov/llama.cpp#10978]
### Git commit

9ba399dfa7f115effc63d48e6860a94c9faa31b2

### Operating systems

Linux

### GGML backends

CPU

### Problem description & steps to reproduce

When compiling with gcc8 in Linux, a linking error occurred.
undefined reference to std::filesystem

### Relevant log output

```shell
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `vtable for std::filesystem::__cxx11::filesystem_error'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator*() const'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `typeinfo for std::filesystem::__cxx11::filesystem_error'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::path::_M_find_extension() const'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::filesystem_error::~filesystem_error()'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::status(std::filesystem::__cxx11::path const&)'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::path::_M_split_cmpts()'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::operator++()'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::directory_iterator::directory_iterator(std::filesystem::__cxx11::path const&, std::filesystem::directory_options, std::error_code*)'
/usr/bin/ld: ../../ggml/src/libggml.so: undefined reference to `std::filesystem::__cxx11::filesystem_error::_M_gen_what()'
```

**Comment by paolovic** [comment]
had the same issue, resolved by updating gcc to 14

**Comment by Levelangel** [comment]
use gcc8 with cmake
after running `cmake -B build -S .`
edit file `build/ggml/src/CMakeLists.txt` and add `link_libraries(stdc++fs)` to it

**Comment by ldhhello** [comment]
I did `cmake -B build -S .` but I cannot find file `build/ggml/src/CMakeLists.txt`.
I'm using Rocky linux 8.10 and GCC version 8.5.0.
I want to resolve this issue without updating my GCC. please help me

**Comment by mayoor** [comment]
> I can confirm that this does indeed fix the build on RHEL 8.10.

required for OL 8 as well

**Comment by fireqp0x** [comment]
It worked in my case (Oracle Linux Server release 8.10).
I didn’t edit `<llama.cpp root>/ggml/src/CMakeLists.txt`.
I just installed gcc-toolset-14-gcc and gcc-toolset-14-gcc-c++, and the build finished successfully.

**Comment by fcorneli** [comment]
For a build on AlmaLinux 8 you indeed need to add:
```
link_libraries(stdc++fs)
```
after
```
add_library(ggml
            ggml-backend-reg.cpp)
```

**Comment by fcorneli** [comment]
For AlmaLinux 8, the following also works:
```
dnf install gcc-toolset-14-gcc gcc-toolset-14-gcc-c++
scl enable gcc-toolset-14 bash
export CUDACXX=/usr/local/cuda-13.1/bin/nvcc
cmake -B build -DGGML_CUDA=ON
cmake --build build --config Release --parallel
```
