### ISSUE TITLE
Issue with install dependancies.

### ISSUE THREAD

**Issue by wereretot** [ggerganov/llama.cpp#7525]
Please include information about your system, the steps to reproduce the bug, and the version of llama.cpp that you are using. If possible, please provide a minimal code example that reproduces the bug.

If the bug concerns the server, please try to reproduce it first using the [server test scenario framework](https://github.com/ggerganov/llama.cpp/tree/master/examples/server/tests).

Collecting numpy~=1.24.4 (from -r ./requirements/./requirements-convert.txt (line 1))
  Using cached numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/rexommendation/Programs/llama.cpp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/rexommendation/Programs/llama.cpp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/rexommendation/Programs/llama.cpp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/rexommendation/Programs/llama.cpp/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-lsk9xfgv/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-lsk9xfgv/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-lsk9xfgv/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

This is after a system update a few days ago when I finally got around to updating my llama.cpp.
6.9.0-1-MANJARO (64-bit)

**Comment by fairydreaming** [comment]
I remember having similar problem, but instead of finding a proper solution I simply downgraded Python to 3.11. With older Python everything works fine.

**Comment by ggerganov** [comment]
Yes, for me the only solution also was to downgrade Python

**Comment by fairydreaming** [comment]
@wereretot if you really need it to work with Python 3.12, you can simply remove the hardcoded versions from pip requirements files and let it find a working combination:

```
diff --git a/requirements/requirements-convert-hf-to-gguf-update.txt b/requirements/requirements-convert-hf-to-gguf-update.txt
index 6ac40261..7132580a 100644
--- a/requirements/requirements-convert-hf-to-gguf-update.txt
+++ b/requirements/requirements-convert-hf-to-gguf-update.txt
@@ -1,2 +1,2 @@
 -r ./requirements-convert.txt
-torch~=2.1.1
+torch
diff --git a/requirements/requirements-convert-hf-to-gguf.txt b/requirements/requirements-convert-hf-to-gguf.txt
index 6ac40261..7132580a 100644
--- a/requirements/requirements-convert-hf-to-gguf.txt
+++ b/requirements/requirements-convert-hf-to-gguf.txt
@@ -1,2 +1,2 @@
 -r ./requirements-convert.txt
-torch~=2.1.1
+torch
diff --git a/requirements/requirements-convert.txt b/requirements/requirements-convert.txt
index 7ab1228c..b57604b7 100644
--- a/requirements/requirements-convert.txt
+++ b/requirements/requirements-convert.txt
@@ -1,5 +1,5 @@
-numpy~=1.24.4
-sentencepiece~=0.2.0
-transformers>=4.40.1,<5.0.0
-gguf>=0.1.0
-protobuf>=4.21.0,<5.0.0
+numpy
+sentencepiece
+transformers
+gguf
+protobuf
```

On my system this installed the following versions:

```
gguf                     0.6.0
numpy                    1.26.4
protobuf                 5.27.0
sentencepiece            0.2.0
torch                    2.3.0
transformers             4.41.1
```

and convert-hf-to-gguf.py seems to be working OK. However, I'm not sure what is the reason for hardcoding the numpy and torch version, so some other script may fail.

**Comment by LucaKoval** [comment]
Has anyone found a more stable solution aside from downgrading Python and editing the `requirements.txt` files?

**Comment by Galunid** [comment]
@LucaKoval There isn't one. The problem is that the numpy version in `requirements.txt` doesn't support python 3.12. So either you downgrade, or bump the version to `1.26.4` (maybe earlier versions work too).

**Comment by LucaKoval** [comment]
Sounds good, thank you!

**Comment by fairydreaming** [comment]
I modified my solution a bit by adding python_version requirement specifiers:

```
diff --git a/requirements/requirements-convert-hf-to-gguf-update.txt b/requirements/requirements-convert-hf-to-gguf-update.txt
index 6ac40261..5b1f01f2 100644
--- a/requirements/requirements-convert-hf-to-gguf-update.txt
+++ b/requirements/requirements-convert-hf-to-gguf-update.txt
@@ -1,2 +1,3 @@
 -r ./requirements-convert.txt
-torch~=2.1.1
+torch~=2.1.1 ; python_version < '3.12'
+torch~=2.3 ; python_version >= '3.12'
diff --git a/requirements/requirements-convert-hf-to-gguf.txt b/requirements/requirements-convert-hf-to-gguf.txt
index 6ac40261..5b1f01f2 100644
--- a/requirements/requirements-convert-hf-to-gguf.txt
+++ b/requirements/requirements-convert-hf-to-gguf.txt
@@ -1,2 +1,3 @@
 -r ./requirements-convert.txt
-torch~=2.1.1
+torch~=2.1.1 ; python_version < '3.12'
+torch~=2.3 ; python_version >= '3.12'
diff --git a/requirements/requirements-convert.txt b/requirements/requirements-convert.txt
index 7ab1228c..923092be 100644
--- a/requirements/requirements-convert.txt
+++ b/requirements/requirements-convert.txt
@@ -1,4 +1,5 @@
-numpy~=1.24.4
+numpy~=1.24.4 ; python_version < '3.12'
+numpy~=1.26.4 ; python_version >= '3.12'
 sentencepiece~=0.2.0
 transformers>=4.40.1,<5.0.0
 gguf>=0.1.0

```

This shall work on both Python 3.11 and Python 3.12

**Comment by Galunid** [comment]
Should be fixed in #8041
