### ISSUE TITLE
Compile bug: ios swift xcode build error when upgrade to llama : use cmake for swift build 

### ISSUE THREAD

**Issue by jiabochao** [ggerganov/llama.cpp#10747]
### Git commit

$git rev-parse HEAD 43ed389a3f102517e6f7d5620d8e451e88afbf27

### Operating systems

Mac

### GGML backends

Metal

### Problem description & steps to reproduce

ios swift xcode build error when upgrade to

- https://github.com/ggerganov/llama.cpp/pull/10525

Before the upgrade, the code compiled successfully. After the upgrade, it throws a compilation error: "Cannot find type 'xxx' in scope."

<img width="1721" alt="image" src="https://github.com/user-attachments/assets/1bc2e76a-158a-4aa3-9755-855930f2f7ed">

### First Bad Commit

43ed389a3f102517e6f7d5620d8e451e88afbf27

### Relevant log output

```shell
/ios/llama.cpp.swift/LibLlama.swift:8:39 Cannot find type 'llama_batch' in scope

/ios/llama.cpp.swift/LibLlama.swift:12:37 Cannot find type 'llama_batch' in scope

/ios/llama.cpp.swift/LibLlama.swift:12:56 Cannot find type 'llama_token' in scope

/ios/llama.cpp.swift/LibLlama.swift:12:76 Cannot find type 'llama_pos' in scope

/ios/llama.cpp.swift/LibLlama.swift:12:99 Cannot find type 'llama_seq_id' in scope

/ios/llama.cpp.swift/LibLlama.swift:27:48 Cannot find type 'llama_sampler' in scope

/ios/llama.cpp.swift/LibLlama.swift:28:24 Cannot find type 'llama_batch' in scope

/ios/llama.cpp.swift/LibLlama.swift:29:31 Cannot find type 'llama_token' in scope

/ios/llama.cpp.swift/LibLlama.swift:44:22 Cannot find 'llama_batch_init' in scope

/ios/llama.cpp.swift/LibLlama.swift:46:23 Cannot find 'llama_sampler_chain_default_params' in scope

/ios/llama.cpp.swift/LibLlama.swift:47:25 Cannot find 'llama_sampler_chain_init' in scope

/ios/llama.cpp.swift/LibLlama.swift:48:9 Cannot find 'llama_sampler_chain_add' in scope

/ios/llama.cpp.swift/LibLlama.swift:48:48 Cannot find 'llama_sampler_init_temp' in scope

/ios/llama.cpp.swift/LibLlama.swift:49:9 Cannot find 'llama_sampler_chain_add' in scope

/ios/llama.cpp.swift/LibLlama.swift:49:48 Cannot find 'llama_sampler_init_dist' in scope

/ios/llama.cpp.swift/LibLlama.swift:53:9 Cannot find 'llama_sampler_free' in scope

/ios/llama.cpp.swift/LibLlama.swift:54:9 Cannot find 'llama_batch_free' in scope

/ios/llama.cpp.swift/LibLlama.swift:55:9 Cannot find 'llama_free' in scope

/ios/llama.cpp.swift/LibLlama.swift:56:9 Cannot find 'llama_free_model' in scope

/ios/llama.cpp.swift/LibLlama.swift:57:9 Cannot find 'llama_backend_free' in scope

/ios/llama.cpp.swift/LibLlama.swift:61:9 Cannot find 'llama_backend_init' in scope

/ios/llama.cpp.swift/LibLlama.swift:62:28 Cannot find 'llama_model_default_params' in scope

/ios/llama.cpp.swift/LibLlama.swift:68:21 Cannot find 'llama_load_model_from_file' in scope

/ios/llama.cpp.swift/LibLlama.swift:77:26 Cannot find 'llama_context_default_params' in scope

/ios/llama.cpp.swift/LibLlama.swift:82:23 Cannot find 'llama_new_context_with_model' in scope

/ios/llama.cpp.swift/LibLlama.swift:100:22 Cannot find 'llama_model_desc' in scope

/ios/llama.cpp.swift/LibLlama.swift:121:21 Cannot find 'llama_n_ctx' in scope

/ios/llama.cpp.swift/LibLlama.swift:142:12 Cannot find 'llama_decode' in scope

/ios/llama.cpp.swift/LibLlama.swift:150:27 Cannot find type 'llama_token' in scope

/ios/llama.cpp.swift/LibLlama.swift:152:24 Cannot find 'llama_sampler_sample' in scope

/ios/llama.cpp.swift/LibLlama.swift:154:12 Cannot find 'llama_token_is_eog' in scope

/ios/llama.cpp.swift/LibLlama.swift:185:12 Cannot find 'llama_decode' in scope

/ios/llama.cpp.swift/LibLlama.swift:211:13 Cannot find 'llama_kv_cache_clear' in scope

/ios/llama.cpp.swift/LibLlama.swift:213:30 Cannot find 'ggml_time_us' in scope

/ios/llama.cpp.swift/LibLlama.swift:215:16 Cannot find 'llama_decode' in scope

/ios/llama.cpp.swift/LibLlama.swift:218:13 Cannot find 'llama_synchronize' in scope

/ios/llama.cpp.swift/LibLlama.swift:220:28 Cannot find 'ggml_time_us' in scope

/ios/llama.cpp.swift/LibLlama.swift:224:13 Cannot find 'llama_kv_cache_clear' in scope

/ios/llama.cpp.swift/LibLlama.swift:226:30 Cannot find 'ggml_time_us' in scope

/ios/llama.cpp.swift/LibLlama.swift:235:20 Cannot find 'llama_decode' in scope

/ios/llama.cpp.swift/LibLlama.swift:238:17 Cannot find 'llama_synchronize' in scope

/ios/llama.cpp.swift/LibLlama.swift:241:28 Cannot find 'ggml_time_us' in scope

/ios/llama.cpp.swift/LibLlama.swift:243:13 Cannot find 'llama_kv_cache_clear' in scope

/ios/llama.cpp.swift/LibLlama.swift:245:24 No exact matches in call to initializer 

/ios/llama.cpp.swift/LibLlama.swift:246:24 No exact matches in call to initializer 

/ios/llama.cpp.swift/LibLlama.swift:254:32 Cannot convert value of type 'Duration' to expected argument type 'Double'

/ios/llama.cpp.swift/LibLlama.swift:255:32 Cannot convert value of type 'Duration' to expected argument type 'Double'

/ios/llama.cpp.swift/LibLlama.swift:272:64 Cannot find 'llama_model_size' in scope

/ios/llama.cpp.swift/LibLlama.swift:273:62 Cannot find 'llama_model_n_params' in scope

/ios/llama.cpp.swift/LibLlama.swift:293:9 Cannot find 'llama_kv_cache_clear' in scope

/ios/llama.cpp.swift/LibLlama.swift:296:60 Cannot find type 'llama_token' in scope

/ios/llama.cpp.swift/LibLlama.swift:299:43 Cannot find type 'llama_token' in scope

/ios/llama.cpp.swift/LibLlama.swift:300:26 Cannot find 'llama_tokenize' in scope

/ios/llama.cpp.swift/LibLlama.swift:302:27 Cannot find type 'llama_token' in scope

/ios/llama.cpp.swift/LibLlama.swift:313:40 Cannot find type 'llama_token' in scope

/ios/llama.cpp.swift/LibLlama.swift:319:23 Cannot find 'llama_token_to_piece' in scope

/ios/llama.cpp.swift/LibLlama.swift:327:30 Cannot find 'llama_token_to_piece' in scope

/ios/llama.cpp.swift/LibLlama.swift:328:33 Generic parameter 'Element' could not be inferred

~/Library/Developer/Xcode/DerivedData/Runner-efnwjojzxwrmmpfdjskgbtmftvem/SourcePackages/checkouts/llama.cpp/Sources/llama/llama.h
~/Library/Developer/Xcode/DerivedData/Runner-efnwjojzxwrmmpfdjskgbtmftvem/SourcePackages/checkouts/llama.cpp/Sources/llama/llama.h:3:10 'llama.h' file not found with <angled> include; use "quotes" instead
```

**Comment by nvoter** [comment]
same issue

**Comment by pgorzelany** [comment]
Can confirm, same issue

**Comment by slaren** [comment]
The way it works now is that you need to build llama.cpp with `cmake`, and then install it using `cmake --install`. This should allow swift to find the llama.cpp library. See the way the CI builds the swift example:

https://github.com/ggerganov/llama.cpp/blob/235f6e14bf0ed0211c51aeff14139038ae1000aa/.github/workflows/build.yml#L573-L592

**Comment by pgorzelany** [comment]
First of all, thank you for providing some clarification. I don't usually use `cmake` so I am not familiar with the build process but the project still exposes a `Package.swift` file which seems to not work currently (even the example SwiftUI projects are broken).

Previously when developing for iOS and MacOS we could point Xcode to the llama.cpp swift package and it would "just work" which was pretty nice. If there are additional steps to be done now, can we have some additional documentation around the process?

**Comment by ggerganov** [comment]
@pgorzelany Doing what the CI workflows do (see slaren's comment) should work.

The CI workflows install the `llama.cpp` binaries into the default system paths so your Swift project will automatically find them. However, you might not always want to do that. Instead, you can build different variants of the binaries and install them into custom paths using `CMAKE_INSTALL_PREFIX`. After that you can point your project to that install location by updating the `Build Settings` in XCode. Here is how I configured the `llama.swiftui` example on my machine:

<img width="864" alt="image" src="https://github.com/user-attachments/assets/eda9bb59-29c5-4a1f-955d-06dea4fa0ba7" />

The process is a bit more involved than before, but it is more flexible and much easier to maintain. It would be useful to have step-by-step instructions added to the example, but I don't have much experience working with XCode (there is stuff like code signing, development teams, etc.), so I am hoping that people who are familiar will contribute and explain how to build a project correctly.

So atm, if you are looking for a point-and-click solution - there isn't one yet. You will need to understand how CMake works and start using it.

**Comment by pgorzelany** [comment]
Thank you. Once I understand how to properly set it up I will try to contribute some documentation around it. This project is used in multiple iOS and MacOS apps and it was very convenient to use it with the Package.swift file, maybe there is a way to modify the Package.swift to work again.

**Comment by Animaxx** [comment]
Hi @ggerganov after I follow the steps in CI, do the CMake and install and updated the search path to `/usr/local/include` and `/usr/local/lib`.  

still getting different errors for Undefined symbols do you have any suggestions?

![Screenshot 2024-12-20 at 12 06 40 AM](https://github.com/user-attachments/assets/e0611047-13bb-42c8-8c65-42bf1fa61e89)

**Comment by Animaxx** [comment]
after run `xcodebuild -scheme llama-Package -destination "generic/platform=macOS"` and use swift package in the project, the app able to build but got Library not loaded error during the running.

dyld[61825]: Library not loaded: @rpath/libggml.dylib

**Comment by Animaxx** [comment]
for iOS build, got error like "Building for 'iOS-simulator', but linking in dylib (/usr/local/lib/libggml.dylib) built for 'macOS'" while build. 

here is the script I am using to update and build
```
if [ ! -d "llama.cpp" ]; then
    git clone https://github.com/ggerganov/llama.cpp
    cd ./llama.cpp
else
    cd ./llama.cpp
    git pull
fi

rm -rf build
mkdir build
cd build
cmake -G Xcode .. \
    -DGGML_METAL_USE_BF16=ON \
    -DGGML_METAL_EMBED_LIBRARY=ON \
    -DLLAMA_BUILD_EXAMPLES=OFF \
    -DLLAMA_BUILD_TESTS=OFF \
    -DLLAMA_BUILD_SERVER=OFF \
    -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"
cmake --build . --config Release -j $(sysctl -n hw.logicalcpu)
sudo cmake --install . --config Release

# build for swift package
cd ..
xcodebuild -scheme llama-Package \
    -destination "generic/platform=macOS" \
    -destination "generic/platform=iOS" \
    clean build
```
and use the package in the Xcode project. please let me know if anything I am missed

**Comment by edisonzf2020** [comment]
me too
![Uploading 截屏2024-12-21 19.20.05.png…]()

**Comment by pgorzelany** [comment]
Was anyone able to solve this issue? I have an iOS project using llama and can't update to the latest version because of this. Any help appreciated!

**Comment by pgorzelany** [comment]
> The way it works now is that you need to build llama.cpp with `cmake`, and then install it using `cmake --install`. This should allow swift to find the llama.cpp library. See the way the CI builds the swift example:
> 
> [llama.cpp/.github/workflows/build.yml](https://github.com/ggerganov/llama.cpp/blob/235f6e14bf0ed0211c51aeff14139038ae1000aa/.github/workflows/build.yml#L573-L592)
> 
> Lines 573 to 592 in [235f6e1](/ggerganov/llama.cpp/commit/235f6e14bf0ed0211c51aeff14139038ae1000aa)
> 
>        - name: Build llama.cpp with CMake 
>          id: cmake_build 
>          run: | 
>            sysctl -a 
>            mkdir build 
>            cd build 
>            cmake -G Xcode .. \ 
>              -DGGML_METAL_USE_BF16=ON \ 
>              -DGGML_METAL_EMBED_LIBRARY=ON \ 
>              -DLLAMA_BUILD_EXAMPLES=OFF \ 
>              -DLLAMA_BUILD_TESTS=OFF \ 
>              -DLLAMA_BUILD_SERVER=OFF \ 
>              -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64" 
>            cmake --build . --config Release -j $(sysctl -n hw.logicalcpu) 
>            sudo cmake --install . --config Release 
>   
>        - name: xcodebuild for swift package 
>          id: xcodebuild 
>          run: | 
>            xcodebuild -scheme llama-Package -destination "${{ matrix.destination }}"

Hi @slaren , thank you for the response. The issue is that we are not able to use it as a system library on iOS since we cannot install llama on iOS. On Mac it may work but we need to somehow embed llama into the iOS app bundle if we would like to ship it. Could you advise som possible ways around it?

**Comment by ggerganov** [comment]
> The issue is that we are not able to use it as a system library on iOS since we cannot install llama on iOS. On Mac it may work but we need to somehow embed llama into the iOS app bundle if we would like to ship it.

Could you provide a reference that shipping libraries on iOS is not possible? Seems hard to imagine that there is such a limitation. There must be some workaround. I just don't have a lot of experience and cannot suggest anything atm, but I doubt there is not way to fix this.

**Comment by MrMage** [comment]
> > The issue is that we are not able to use it as a system library on iOS since we cannot install llama on iOS. On Mac it may work but we need to somehow embed llama into the iOS app bundle if we would like to ship it.
> 
> Could you provide a reference that shipping libraries on iOS is not possible? Seems hard to imagine that there is such a limitation. There must be some workaround. I just don't have a lot of experience and cannot suggest anything atm, but I doubt there is not way to fix this.

Sorry for the drive-by, but my understanding is as follows; maybe it can provide some additional insights to avoid misunderstandings here:

The blocking issue with the build system changes is that, while iOS _does_ support linking against dynamic libraries, it only supports that through the use of _Frameworks_. I.e., you are _not_ allowed to ships a `.dylib` file as part of your app bundle on iOS, but you _are_ allowed to [essentially ship the same, also dynamically linked, code in a `.framework` bundle](https://stackoverflow.com/a/73864903/153354). On macOS, this limitation does not exist; it allows you to ship `.dylib` files as part of your app bundle.

So I think what needs to be done would be to add options to the llama.cpp's CMake build system to have it generate a `.framework` bundles instead of a `.dylib` files. I have no experience with CMake, so I can't provide more details on how to accomplish this, but I hope this at least provides a starting point for investigation.

**Comment by pgorzelany** [comment]
Thanks for the investigation. Maybe its possible to build llama as a static library and embed that in the iOS app?

**Comment by pgorzelany** [comment]
> > The issue is that we are not able to use it as a system library on iOS since we cannot install llama on iOS. On Mac it may work but we need to somehow embed llama into the iOS app bundle if we would like to ship it.
> 
> Could you provide a reference that shipping libraries on iOS is not possible? Seems hard to imagine that there is such a limitation. There must be some workaround. I just don't have a lot of experience and cannot suggest anything atm, but I doubt there is not way to fix this.

[Here are Apple docs](https://developer.apple.com/documentation/packagedescription/target/systemlibrary%28name%3Apath%3Apkgconfig%3Aproviders%3A%29?utm_source=chatgpt.com) describing the use of a systemLibrary target in a Swift package.

The way I understand it, if you expose llama.cpp as a systemLibrary it has to be actually installed on the system. This is possible on MacOS but you can't just install system libraries on iOS.  So I am just saying the current Package.swift setup feels incorrect.

You can ship dynamic libraries as Frameworks as discussed above but I am not sure if there is a way to expose them as a Swift package.

One possible route forward would be to build llama using CMake for all Apple platforms separately and then bundle that up in an [XCFramework ](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle) and then wrap that into a [Swift package as a binaryTarget](https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages).

**Comment by MrMage** [comment]
> To add to that, from an https://github.com/ggerganov/llama.cpp/issues/11113#issuecomment-2574061157, CMake should support building frameworks through [CMAKE_FRAMEWORK](https://cmake.org/cmake/help/latest/variable/CMAKE_FRAMEWORK.html). So definitely look into this as well.

For what it's worth, I am only using llama.cpp for my macOS app where `dylib`s are allowed. So I am personally not affected by this issue, but I figured I'd provide some insight. That being said, I remember trying the `CMAKE_FRAMEWORK` option when building llama.cpp, and it did _not_ work for me for llama.cpp (and I've seen others reports here of the same).

> The way I understand it, if you expose llama.cpp as a systemLibrary it has to be actually installed on the system. This is possible on MacOS but you can't just install system libraries on iOS. So I am just saying the current Package.swift setup feels incorrect.

Now, I can't expect my Mac app's users to install llama.cpp on their own, but I found a way around this: I am still adding the llama.cpp Swift package to my macOS app, but I am _also_ adding references to the built `dylib`s to my app's target, telling Xcode to copy these dylibs into the app's frameworks folder upon build, plus [the build settings from above that ensure that Xcode also looks for the same copies of these libraries when e.g. referencing header files](https://github.com/ggerganov/llama.cpp/issues/10747#issuecomment-2538203367).

That way, I can have SwiftPM believe that it's using the system libraries, but in reality ship those libraries as part of the app bundle.

I could imagine that a similar approach might work for iOS — but only if one can get llama.cpp to emit frameworks instead of `dylib`s. That being said, I could also imagine that building static versions of these libraries might work, but I think the integration with SwiftPM would be more complex then. Similarly, the approach of building an `XCFramework` would probably be ideal — if one can get llama.cpp's build process to emit one, and if Xcode can be convinced to use that without issues. I guess at that point, one would simply drop the reference to the llama.cpp "system library" package altogether.

**Comment by pgorzelany** [comment]
I tried to make the XCFramework approach work for several hours but wasn’t able to. In the end I forked the project, reverted the Package.swift changes and adjusted it for the latest project structure. It now builds for iOS as before so it’s a potential workaround.

**Comment by Animaxx** [comment]
Good to see more discussion on this topic!

**Comment by hnipps** [comment]
I remember reading [@philippzagar used the XCFramework approach a while ago](https://github.com/ggerganov/llama.cpp/discussions/4423). Their fork is quite far behind and I'm not familiar enough with the ecosystem to bring it up to date but maybe it'll help y'all.

**Comment by hnipps** [comment]
@pgorzelany any chance you can share your workaround?

**Comment by yhondri** [comment]
Hi @hnipps, here is my approach that is similar to what @pgorzelany said:
In my case I created a new SPM and packaged llama sources based on the old version of the Package.Swift file of llamacpp. 
[Old version of llama.cpp Package.swift](https://github.com/ggerganov/llama.cpp/commit/43ed389a3f102517e6f7d5620d8e451e88afbf27#diff-f913940c58e8744a2af1c68b909bb6383e49007e6c5a12fb03104a9006ae677e)

I think you can skip the step of creating a new package and just put the Package.swift code that I wrote next, in the llama's Package.swift file. 

Here is the structure of my Package.swift. 

- LlamaKit 
  - Package.swift 
  - Sources 
    - llama 
    - LlamaKit 

Here is the code of Package.swift. 

```
import PackageDescription

var sources = [
    "src/llama.cpp",
    "src/llama-adapter.cpp",
    "src/llama-arch.cpp",
    "src/llama-chat.cpp",
    "src/llama-batch.cpp",
    "src/llama-context.cpp",
    "src/llama-cparams.cpp",
    "src/llama-grammar.cpp",
    "src/llama-hparams.cpp",
    "src/llama-impl.cpp",
    "src/llama-kv-cache.cpp",
    "src/llama-mmap.cpp",
    "src/llama-model.cpp",
    "src/llama-model-loader.cpp",
    "src/llama-quant.cpp",
    "src/llama-sampling.cpp",
    "src/llama-vocab.cpp",
    "src/unicode.cpp",
    "src/unicode-data.cpp",
    "ggml/src/ggml.c",
    "ggml/src/ggml-alloc.c",
    "ggml/src/ggml-backend.cpp",
    "ggml/src/ggml-backend-reg.cpp",
    "ggml/src/ggml-quants.c",
    "ggml/src/ggml-threading.cpp",
    "ggml/src/gguf.cpp",
    "ggml/src/ggml-cpu/ggml-cpu.c",
    "ggml/src/ggml-cpu/ggml-cpu.cpp",
    "ggml/src/ggml-cpu/ggml-cpu-aarch64.cpp",
    "ggml/src/ggml-cpu/ggml-cpu-hbm.cpp",
    "ggml/src/ggml-cpu/ggml-cpu-quants.c",
    "ggml/src/ggml-cpu/ggml-cpu-traits.cpp"
]

var resources: [Resource] = []
var linkerSettings: [LinkerSetting] = []
var cSettings: [CSetting] =  [
    .unsafeFlags(["-Wno-shorten-64-to-32", "-O3", "-DNDEBUG"]),
    .unsafeFlags(["-fno-objc-arc"]),
    .headerSearchPath("ggml/src"),
    .headerSearchPath("ggml/src/ggml-cpu"),
    // NOTE: NEW_LAPACK will required iOS version 16.4+
    // We should consider add this in the future when we drop support for iOS 14
    // (ref: ref: https://developer.apple.com/documentation/accelerate/1513264-cblas_sgemm?language=objc)
    // .define("ACCELERATE_NEW_LAPACK"),
    // .define("ACCELERATE_LAPACK_ILP64")
    .define("GGML_USE_CPU"),
]

#if canImport(Darwin)
sources.append("ggml/src/ggml-common.h")
sources.append("ggml/src/ggml-metal/ggml-metal.m")
resources.append(.process("ggml/src/ggml-metal/ggml-metal.metal"))
linkerSettings.append(.linkedFramework("Accelerate"))
cSettings.append(
    contentsOf: [
        .define("GGML_USE_ACCELERATE"),
        .define("GGML_USE_METAL"),
    ]
)
#endif

let package = Package(
    name: "LlamaKit",
    platforms: [
        .macOS(.v15),
        .iOS(.v18)
   ],
    products: [
        .library(
            name: "LlamaKit",
            targets: ["LlamaKit"]),
    ],
    dependencies: [],
    targets: [
        .target(
            name: "LlamaKit",
            dependencies: ["llama"],
            path: "Sources/LlamaKit",
            swiftSettings: [
                .unsafeFlags(["-Onone"], .when(configuration: .release))
            ]
        ),
        .target(
            name: "llama",
            path: "Sources/llama",
            exclude: [
                "build",
                "cmake",
                "examples",
                "scripts",
                "models",
                "tests",
                "CMakeLists.txt",
                "Makefile",
                "ggml/src/ggml-metal/ggml-metal.metal"
            ],
            sources: sources,
            resources: resources,
            publicHeadersPath: "spm-headers",
            cSettings: cSettings,
            swiftSettings: [  // Disable optimization because model generate random response in release mode.
                .unsafeFlags(["-Onone"], .when(configuration: .release))
            ],
            linkerSettings: linkerSettings
        ),
        .testTarget(
            name: "LlamaKitTests",
            dependencies: ["LlamaKit"]
        )
    ],
    cxxLanguageStandard: .cxx17
)

```

**Comment by Animaxx** [comment]
thank you @yhondri! are you going to create PR to submit your Package.Swift?

**Comment by yhondri** [comment]
Hi @Animaxx, I could do it, but I believe the team wouldn’t accept it due to the new way of building and delivering the library with CMake. Right now, I think the idea is to make the build process work with CMake.

**Comment by tingyuchang** [comment]
@yhondri  thanks for your solution, but I think it should add `.headerSearchPath("ggml/include")` otherwise it will show `gguf.h file not found` error.

**Comment by NegiAbhijeet** [comment]
whats next, any solution?

**Comment by ggerganov** [comment]
Could someone take a look at the https://github.com/allenai/OLMoE.swift project, see how they have integrated `llama.cpp` into the iOS app and provide a short summary here?

**Comment by MrMage** [comment]
> Could someone take a look at the [allenai/OLMoE.swift](https://github.com/allenai/OLMoE.swift) project, see how they have integrated `llama.cpp` into the iOS app and provide a short summary here?

They are using commit `cc98896db858df7aa40d0e16a505883ef196a482` of `llama.cpp` (see [their xcode project file](https://github.com/allenai/OLMoE.swift/blob/9c33a1e3205c36ff407981d83e494cb4fb4bdae3/OLMoE.swift.xcodeproj/project.pbxproj#L514C16-L514C56)), which predates the packaging changes.

**Comment by blaineam** [comment]
For some reason I cannot get metal to work even though llama.cpp compiles on swift with that work around. that fix was applied to the current commit on the default branch of llama.cpp
```
ggml_metal_init: allocating
ggml_metal_init: picking default device: Apple A18 Pro GPU
ggml_metal_init: default.metallib not found, loading from source
ggml_metal_init: GGML_METAL_PATH_RESOURCES = nil
ggml_metal_init: error: could not use bundle path to find ggml-metal.metal, falling back to trying cwd
ggml_metal_init: loading 'ggml-metal.metal'
ggml_metal_init: error: Error Domain=NSCocoaErrorDomain Code=260 "The file “ggml-metal.metal” couldn’t be opened because there is no such file." UserInfo={NSFilePath=ggml-metal.metal, NSURL=ggml-metal.metal -- file:///, NSUnderlyingError=0x3025a39c0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
ggml_backend_metal_device_init: error: failed to allocate context
llama_init_from_model: failed to initialize Metal backend
```

**Comment by ggerganov** [comment]
We have to make the CMake work. The build solutions based on `Package.swift` posted here are not an option - it's not only difficult to maintain, but it will completely stop working when `ggml` becomes a git submodule, because SPM does not support submodules.

Let's focus on making the CMake build work.

Can someone explain to me why the solution in https://github.com/ggml-org/llama.cpp/issues/10747#issuecomment-2538203367 does not work? I just followed the steps with a fresh clone of the project and adding the binaries to the project makes it build successfully and run on my iPhone:

```bash
mkdir build-spm-ios
cd build-spm-ios

cmake -B build -G Xcode \
    -DCMAKE_INSTALL_PREFIX=tmp \
    -DGGML_METAL_USE_BF16=ON \
    -DGGML_METAL_EMBED_LIBRARY=ON \
    -DLLAMA_BUILD_EXAMPLES=OFF \
    -DLLAMA_BUILD_TESTS=OFF \
    -DLLAMA_BUILD_SERVER=OFF \
    -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=14.0 \
    -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM=ggml ..

cmake --build build --config Release -j $(sysctl -n hw.logicalcpu) -- CODE_SIGNING_ALLOWED=NO

cmake --install build --config Release
```

In XCode, open the `llama.swiftui`, set Release build and set the following paths:

![Image](https://github.com/user-attachments/assets/e0ff18d6-ec4c-442a-9431-cec1bd0e2b63)

Add the ggml/llama.cpp binaries to the project:

![Image](https://github.com/user-attachments/assets/6b2d29a0-0eb8-442c-a0cc-236e815488d3)

And run it:

![Image](https://github.com/user-attachments/assets/053d98b3-6975-429e-b3ec-000083decf49)
![Image](https://github.com/user-attachments/assets/0cd5a8d5-da05-48b8-bf93-9edee8342762)

What is the problem with this workflow?

**Comment by tladesignz** [comment]
Seriously, a manually put together build like that with a dozen of magic values no one coming from outside will find and understand on their own isn't a solution for people who just want to put together an iOS app and who will need to keep this maintained and shared between a team.

That's the start of a proper build script, but not a solution.

If you want to follow the `cmake` route, we need to provide a proper script which one just needs to feed their wanted targets and then builds that reliably.

This build script should also end up creating a proper [xcframework](https://developer.apple.com/documentation/xcode/creating-a-multi-platform-binary-framework-bundle) which can be easily dropped in one's Xcode project without messing with linker flags and can be referenced with SPM.

I can help with that, if you want, and we can put together something similar to https://github.com/greatfire/curl-apple/blob/main/build-apple.sh.

BTW: Good ol' [CocoaPods](https://cocoapods.org) actually has support for submodules and fancy build scripts. I know it isn't popular with the kids nowadays, but it is better documented, has less bugs and more features than SPM, still. (Which is actually a disgrace for Apple…)

**Comment by ggerganov** [comment]
> > What is the problem with this workflow?
> 
> The problem with this workflow is that Apple does not allow apps on iOS (and all the related platforms) to use dynamic libraries (`.dylib` files); those libraries **must** be wrapped in a `.framework` bundle (i.e. a fancy directory structure).

Ok, let's find a way to wrap it. A quick google search says that `lipo` is a tool that can be used to wrap the binaries in a framework:

https://stackoverflow.com/a/62962630

**Comment by tladesignz** [comment]
> Ok, let's find a way to wrap it. A quick google search says that `lipo` is a tool that can be used to wrap the binaries in a framework:
> 
> https://stackoverflow.com/a/62962630

This is solved. Just have a look at this build script. Everything we need to do is in there:

https://github.com/greatfire/curl-apple/blob/main/build-apple.sh.

The part where it builds OpenSSL and libcurl obviously should be replaced with the llama.cpp build.

Then
- "fatten" the libs, meaning combining x86_64 and arm64 builds in one dylib each (except iOS phone/visionOS/tvOS/watchOS production builds, there's currently only arm64 needed)
- Create a `framework` per platform out of all the `dylib`s. (platforms: macOS, iOS, iOS simulator, visionOS, visionOS simulator and optionally tvOS, tvOS simulator, and, yes far out, watchOS and watchOS simulator) 
- Create a `xcframework` out of all the `framework`s.

**Comment by ggerganov** [comment]
> I can help with that, if you want, and we can put together something similar to https://github.com/greatfire/curl-apple/blob/main/build-apple.sh.

Yes, any help would be appreciated.

Seems we just need to setup a CI to prepare the `xcframework` and include in the releases. We can start with iOS since I have verified that this works and then add the rest of the platforms.

**Comment by tladesignz** [comment]
I have zero knowledge of cmake, and it doesn't actually make a warm welcome, so I'd appreciate you starting a script which provides an easy, stable build for macOS, iOS and iOS simulator by default, or a subset of it when requested via a CLI option.

I can then add all the Apple-specific bundling when we have that.

**Comment by ggerganov** [comment]
Can't work on this atm, so let's wait if someone from the community will help out. To summarize, all the necessary steps are here:

https://github.com/ggml-org/llama.cpp/issues/10747#issuecomment-2667937188

https://github.com/ggml-org/llama.cpp/issues/10747#issuecomment-2668613688

**Comment by danbev** [comment]
> I have zero knowledge of cmake, and it doesn't actually make a warm welcome, so I'd appreciate you starting a script 

I've created this [commit](https://github.com/danbev/llama.cpp/commit/45776610004698e3d4ac36fc085d32b426636c6f) which contains a start for the cmake changes which hopefully might help. 

I've tested this by running the [build-xcframework.sh](https://github.com/danbev/llama.cpp/blob/xcframework-build/build-xcframework.sh) script. And then used the generated XCFramework with the [llama.swiftui](https://github.com/danbev/llama.cpp/tree/xcframework-build/examples/llama.swiftui#building) example and was able to build the project and run (using the simulator).

_Note: I did run into the following error when trying to load a model in the simulator, but I also ran into this earlier when using the .dylib's_:
```console
ggml_metal_init: error: load pipeline error: Error Domain=CompilerError Code=2 "only 14 constant buffers binding are supported in the simulator but 16 were used" UserInfo={NSLocalizedDescription=only 14 constant buffers binding are supported in the simulator but 16 were used}
ggml_backend_metal_device_init: error: failed to allocate context
llama_init_from_model: failed to initialize Metal backend
Could not load context!
Error: The operation couldn’t be completed. (llama_swiftui.LlamaError error 0.)
```

**Comment by ggerganov** [comment]
Added a comment to the commit - not sure if it is visible: https://github.com/danbev/llama.cpp/commit/45776610004698e3d4ac36fc085d32b426636c6f#r152808702

Maybe better to start a PR to be able to discuss more easily.

**Comment by danbev** [comment]
> Added a comment to the commit - not sure if it is visible: [danbev@4577661#r152808702](https://github.com/danbev/llama.cpp/commit/45776610004698e3d4ac36fc085d32b426636c6f#r152808702)
> 
> Maybe better to start a PR to be able to discuss more easily.

Absolutely, I'll open a PR in the morning 👍

**Comment by jkrukowski** [comment]
hi all, not sure if it's still relevant but I've created a small PoC repo https://github.com/jkrukowski/llama.cpp.xcframework 
It's an umbrella Swift Package that wraps llama binary XCFramework. On top of that it's got a GitHub action that could once again day pull the newest llama.cpp release, create xcframework and upload and tag a new sem ver release in that repo. Hope it's useful
