### ISSUE TITLE
Compile bug: I'm trying to compile llama.cpp with SYCL support on Arch Linux with the glibc 2.41+r2+g0a7c7a3e283a-1

### ISSUE THREAD

**Issue by dpriedel** [ggerganov/llama.cpp#11713]
### Git commit

HEAD as of the time I post this

9ab42dc722ad19a12af80f38a06474d498f96da3

### Operating systems

Linux

### GGML backends

SYCL

### Problem description & steps to reproduce

I'm trying to compile llama.cpp with SYCL support on Arch Linux with the glibc 2.41+r2+g0a7c7a3e283a-1 and gcc 14.2.1+r730+gc061ad5a36ba-1 packages.  Prior to installing these updates I had no problems with the compile.

I am also using the Intel oneAPI Base Toolkit version 2025.0.1

### First Bad Commit

N/A

### Compile command

```shell
I do `rm -rf build` and then

cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DGGML_SYCL=ON -DCMAKE_C_COMPILER=icx -DCMAKE_CXX_COMPILER=icpx -DLLAMA_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
```
followed by:

 cmake --build build --config Release -j 10

### Relevant log output

```shell
There are multiple instances of the following type of output

In file included from /vol_KUtil2/LLM_Models/llama.cpp/ggml/src/ggml-sycl/conv.cpp:13:
In file included from /vol_KUtil2/LLM_Models/llama.cpp/ggml/src/ggml-sycl/conv.hpp:16:
In file included from /vol_KUtil2/LLM_Models/llama.cpp/ggml/src/ggml-sycl/common.hpp:16:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/fstream:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/istream:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/ios:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/iosfwd:42:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/bits/postypes.h:40:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/14.2.1/../../../../include/c++/14.2.1/cwchar:44:
In file included from /usr/include/wchar.h:30:
/usr/include/bits/floatn.h:79:52: error: unsupported machine mode '__TC__'
   79 | typedef _Complex float __cfloat128 __attribute__ ((__mode__ (__TC__)));
      |                                                    ^
```

**Comment by qnixsynapse** [comment]
This is the SYCL compiler's fault and not llama.cpp. I too encountered that while working in this PR ([comment](https://github.com/ggerganov/llama.cpp/pull/11515#issuecomment-2631415346))

I think they ship a dated version of compiler. Please report on their repository.

For now, downgrade glibc to make the SYCL work again.

**Comment by dpriedel** [comment]
I'm trying to make a small test case which reproduces the problem....
