### ISSUE TITLE
Ambiguous call of overloaded forward

### ISSUE THREAD

**Issue by themanyone** [ggerganov/llama.cpp#5042]
Compilation with `make LLAMA_CUBLAS=1` fails with several ambiguous forwards.

```
oat, 16>, ggml_backend_buffer_type> >; typename __gnu_cxx::__alloc_traits<_Allocator>::rebind<std::pair<const _Key, _Tp> > = __gnu_cxx::__alloc_traits<std::allocator<std::pair<const std::array<float, 16>, ggml_backend_buffer_type> >, std::pair<const std::array<float, 16>, ggml_backend_buffer_type> >::rebind<std::pair<const std::array<float, 16>, ggml_backend_buffer_type> >; typename _Allocator::value_type = std::pair<const std::array<float, 16>, ggml_backend_buffer_type>]’:
ggml-cuda.cu:10741:31:   required from here
/usr/include/c++/13/bits/stl_map.h:608:61: error: call of overloaded ‘forward<std::array<float, 16>&>(std::array<float, 16>&)’ is ambiguous
  608 |           return _M_t._M_emplace_unique(std::forward<_Args>(__args)...);
      |                                        ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/c++/13/bits/move.h:70:1: note: candidate: ‘constexpr _Tp&& std::forward(typename remove_reference<_Functor>::type&) [with _Tp = array<float, 16>&; typename remove_reference<_Functor>::type = array<float, 16>&]’
   70 |     forward(typename std::remove_reference<_Tp>::type& __t) noexcept
      | ^   ~~~
/usr/include/c++/13/bits/move.h:82:1: note: candidate: ‘constexpr _Tp&& std::forward(typename remove_reference<_Functor>::type&&) [with _Tp = array<float, 16>&; typename remove_reference<_Functor>::type = array<float, 16>&]’
   82 |     forward(typename std::remove_reference<_Tp>::type&& __t) noexcept
      | ^   ~~~
make: *** [myMakefile:430: ggml-cuda.o] Error 1
```

Ghd, the relevant lines in ggml-cuda.cu:10741:31:

```    struct ggml_backend_buffer_type buft {
        /* .iface   = */ ggml_backend_cuda_split_buffer_type_interface,
        /* .context = */ new ggml_backend_cuda_split_buffer_type_context{tensor_split_arr},
    };

    auto result = buft_map.emplace(tensor_split_arr, buft);
    return &result.first->second;
}
```

**Comment by themanyone** [comment]
$ git bisect bad
e7e4df031b9e29d4b55a4e0b0295187f6b213db1 is the first bad commit
commit e7e4df031b9e29d4b55a4e0b0295187f6b213db1
Author: slaren <slarengh@gmail.com>
Date:   Fri Jan 12 20:07:38 2024 +0100

**Comment by themanyone** [comment]
Tried again with latest pull of tag b1960.
I can't figure this out. It's trying to add some tensor to an array via an overloaded template that is always ambiguous, no matter how I change it up. I looked at the function candidates in bits, and it's not clear which one to use, or how to use it. I tried stripping the function down to its function definition, and having the AI generate the function. It generates the same errors. Which makes me think the offending function is AI-generated. 

I can make it compile by using a "stub return" (returning nullptr). Of course, this code is not ideal.
`return (ggml_backend_buffer_type_t)nullptr;`

**Comment by slaren** [comment]
Since this is obviously a toolchain issue (which you seem to be aware of, considering you mention having to use `-allow-unsupported-compiler` in a different issue), why not spend the time updating your toolchain instead of trying random changes?

**Comment by themanyone** [comment]
It's fine. The  The -allow-unsupported-compiler doesn't matter. I get the same error without it.

"unsupported compiler is Nvidia's own CUDA host_config.h complaining about Nvidia's own compiler, `nvcc` version 12.3 being > 12. It's an issue with CUDA 12.3. I should probably bug report it over at Nvidia. Good idea!

**Comment by slaren** [comment]
I am also using nvcc 12.3 without problems. My guess is that it is an issue with the host compiler, or possibly with the version of the C++ standard library. We know that at least it works with gcc 12.3.0 (what I use), whatever version of gcc is used in the CI, the current version of MSVC, and also with the hip compiler, which should be some version of clang. So at least, this isn't a very common issue. I would try updating your host compiler first.

**Comment by themanyone** [comment]
I can use any compiler I want, clang, tcc, gcc 13. They all work.
`CC=tcc CXX=clang++ LLAMA_CUDA_F16=1 LLAMA_CUBLAS=1 make -j 8`

It still complains about `nvcc` version. Ironically, the incompatible `host_config.h` and `crt` are distributed in the same package as `cuda-nvcc-12-3`. It could just be the Linux packager over at Nvidia included the wrong header versions.

I can downgrade, borrow the `nvcc` compiler from CUDA v12.0 package. That would also work.

```
# files cuda-nvcc-12-3-12.3.107-1.x86_64.rpm
Repo        : cuda
Matched from:
Filename    : /usr/local/cuda-12.3/targets/x86_64-linux/include/crt/host_config.h
Filename    : /usr/local/cuda-12.3/bin/nvcc
...
```

**Comment by themanyone** [comment]
FYI: update.
The reason I could not make this code work properly with `gcc-13` is I was running into the old [_GLIBC bug_](https://www.win.tue.nl/~aeb/linux/misc/gcc-semibug.html). You see, GLIBC changed the way memove and memcpy worked in 2012, introducing new bugs. And lots of code depended on the old behavior. So `gcc` versions >=13 started *automatically* substituting its own version of these functions. Of course, C++ couldn't tell me this. It just kept saying there was an ambiguous copy or move operation going on. That's why we have to compile on an older machine. Or piece together a private `gcc-12` toolchain to build stuff.

The crux of the matter is that cuBLAS comes precompiled with the newer `memcpy@GLIBC_2.14` and `llama.cpp` is expecting `memcpy@GLIBC_2.2.5`. So `gcc-13` happily substitutes `memcpy@GLIBC_2.14` in its place, rendering `bits` templates ambiguous. I expect the redundant bits templates will some day go away, and we'll be able to use newer compilers.
