### ISSUE TITLE
Bug: ggml/src/ggml-cpu/ggml-cpu.c:2373: error: undefined reference to 'getcpu'

### ISSUE THREAD

**Issue by dspasyuk** [ggerganov/llama.cpp#10352]
### What happened?

I keep seeing this bug on various CentOS and Roku Linux distros with glibs > 2.28 but less than 2.33 

Changing this line in ggml/src/ggml-cpu/ggml-cpu.c:2373 

#if __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ > 28) || defined(__COSMOPOLITAN__)

to 

#if __GLIBC__ > 2 || (__GLIBC__ == 2 && __GLIBC_MINOR__ > 33) || defined(__COSMOPOLITAN__)

fixes the issue for all of my setups. Could we make this permanent? 

### Name and Version

ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
version: 4104 (0fff7fd7)
built with cc (GCC) 9.3.0 for x86_64-pc-linux-gnu

### Relevant log output

```shell
ggml/src/ggml-cpu/ggml-cpu.c:2373: error: undefined reference to 'getcpu'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1240: llama-batched] Error 1
make: *** Waiting for unfinished jobs....
ggml/src/ggml-cpu/ggml-cpu.c:2373: error: undefined reference to 'getcpu'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1285: llama-gguf] Error 1
ggml/src/ggml-cpu/ggml-cpu.c:2373: error: undefined reference to 'getcpu'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1577: llama-vdot] Error 1
ggml/src/ggml-cpu/ggml-cpu.c:2373: error: undefined reference to 'getcpu'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1582: llama-q8dot] Error 1
ggml/src/ggml-cpu/ggml-cpu.c:2373: error: undefined reference to 'getcpu'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1327: llama-bench] Error 1
ggml/src/ggml-cpu/ggml-cpu.c:2373: error: undefined reference to 'getcpu'
collect2: error: ld returned 1 exit status
make: *** [Makefile:1245: llama-batched-bench] Error 1
```

**Comment by ggerganov** [comment]
Unless it somehow breaks some other environments, I don't see a problem to make this permanent. Let's merge it and see how it goes.

**Comment by FirstTimeEZ** [comment]
seems like it caused a test to fail

https://github.com/ggml-org/ci/tree/results/llama.cpp/a4/3178299c2f74f14bcfc659bfd9fd32d931d1f4/ggml-4-x86-cuda-v100

**Comment by ggerganov** [comment]
More likely caused by https://github.com/ggerganov/llama.cpp/pull/10318

**Comment by FirstTimeEZ** [comment]
```
�[1;32mOK�[0m
  MUL_MAT(type_a=f16,type_b=f16,m=16,n=1,k=256,bs=[1,1],nr=[1,1],per=[0,1,2,3]): ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
ggml_backend_cuda_graph_compute: disabling CUDA graphs due to GPU architecture
/home/ggml/work/llama.cpp/ggml/src/ggml-cuda/mmv.cu:156: GGML_ASSERT(src1->type == GGML_TYPE_F32) failed
```

yeah that makes sense

**Comment by FirstTimeEZ** [comment]
I made an issue about it https://github.com/ggerganov/llama.cpp/issues/10356

**Comment by dspasyuk** [comment]
Many thanks guys!
